### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by tgiani** [wilsonmr/anvil#10]
https://github.com/wilsonmr/norm_flow_model/blob/d302b2421e4a929c608dd216da62d301d8267bbc/norm_flow_pytorch.py#L329

@wilsonmr  why are you using ```reversed``` here? Is this the implementation of ```f^{-1}(z)``` ?

**Comment by tgiani** [comment]
https://github.com/wilsonmr/norm_flow_model/blob/d302b2421e4a929c608dd216da62d301d8267bbc/norm_flow_pytorch.py#L352
shouldn't you use ```reversed``` here? According to Eq.12 to build ```f``` you want to apply the last layer first

**Comment by tgiani** [comment]
however you are computing the jacobian consistently so it doesn t really matter I guess

**Comment by wilsonmr** [comment]
Exactly, to summarise the conversation we had in case somebody else is thinking the same thing:

 - whilst in the construction of `NormalisingFlow` we refer to i_affine but these essentially labelled in the opposite way to in the paper. Where the first applied network is denoted as g_n in eq (12).
- regardless of labels as long as the direction in which the networks are applied is the opposite for f(\phi) and f^-1(z) then the model is internally consistent.

I think for now we will leave it but perhaps if it's a common cause of confusion we could swap them
