### ISSUE TITLE
Project* modules should be split up

### ISSUE THREAD

**Issue by wilsonmr** [wilsonmr/anvil#42]
Opening this because we may want to do it at some point

The Project* modules in my opinion should instead be split into the project R->S and S->R and then there could be a class which sandwich some combination of these. Would be useful if we wanted to test if we really need a base distribution on S transformed onto R or whether we could just use a generic base distribution and only have to transform the output of network onto S

**Comment by jmarshrossney** [comment]
This is solved in #46 :)
