### ISSUE TITLE
nans and infs for L>=8

### ISSUE THREAD

**Issue by c-j-johnston** [wilsonmr/anvil#6]
I've been trying to train for L to get an idea of training times/potential optimisations but the loss values for lattices of 8x8 and above all give `-inf` and `nan`. Looking more closely, we get an array of `nan` when we print the output of line 98 of `phi_four.py`:  
`phi = model.inverse_map(z)`.
I've gone further into the code and checked the lines in `norm_flow_pytorch.AffineLayer.inverse_coupling_layer`. All are fully defined when calculating the first loss, but this loss still comes to `nan`. Then when computing the second loss, `s_out` and `t_out` and therefore `phi_b` and the left half of `phi_out` are arrays of `nan`s -- this makes me think the problem could be in the `_s_output` and `_t_output` methods; possibly something to do with the activation functions.
I've tried increasing the number of affine layers and their sizes in the model to no avail. L=6 is still working fine.

**Comment by wilsonmr** [comment]
Possibly for the larger lattices we need to change the initialisation. Recall the transformation has an `exp` in it, so if weights are intialized wrong then this thing could be huge Increasing number of layers and units is not going to help this if it is the case.

I'll have a look at the initialisation

**Comment by wilsonmr** [comment]
Actually I was just looking and I think I know the problem basically since we are returning log p tilde we can avoid some exponentiating, will try and fix!
