### ISSUE TITLE
Parsing info from trained models could be improved.

### ISSUE THREAD

**Issue by wilsonmr** [wilsonmr/anvil#62]
We use `collect` in a few places where we don't need to and instead should do something like in:

https://github.com/wilsonmr/anvil/blob/dca2dfe1e7c00682b113bfa459d64ecb2d7e5778/anvil/config.py#L130

**Comment by jmarshrossney** [comment]
Yeah. The only things we end up needing (so far) are:
- geometry
- base distribution
- target
- model

The model is annoying though, because if we have e.g.
```python
def produce_model_from_training(self, training_context):
```
Then (I think) we also need a separate action to load it - a clone of `loaded_model` - which is very annoying. I'm sure there must be a workaround but haven't thought of one yet.

**Comment by wilsonmr** [comment]
I think that'd be fine in the sense that we would make a function which is called `loaded_trained_model` which calls `loaded_model` on the `model_from_training` and then update all sampling related things to rely on this model..

**Comment by wilsonmr** [comment]
because in training we never load model from the training, do we? In sampling we never would have not trained the model

**Comment by jmarshrossney** [comment]
Yeah I guess that's not too weird. I was thinking it was strange to distinguish between loading a partially trained model to continue training, and loading a (potentially partially) trained model to sample, but it's probably not a big deal.

**Comment by wilsonmr** [comment]
Yeah a little weird. The loaded_model could always be replaced by an explicit node but this seems overly complicated considering the training and sampling are two different scripts.

**Comment by wilsonmr** [comment]
Ok so now I need to rethink this after #68
